apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter-notebook
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: cluster.yumenomatayume.local.net
    http:
      paths:
      - path: /jupyter-notebook
        pathType: Prefix
        backend:
          service:
            name: jupyter-notebook
            port:
              number: 80
