---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jupyter-notebook
  name: jupyter-notebook
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block
