kind: Service
apiVersion: v1
metadata:
  name: jupyter-notebook
spec:
  type: LoadBalancer
  selector:
    app: jupyter-notebook
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8888
