---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-exporter
  labels:
    app: vmware-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmware-exporter
  template:
    metadata:
      labels:
        app: vmware-exporter
    spec:
      containers:
        - name: vmware-exporter
          image: pryorda/vmware_exporter:latest
          envFrom:
            - secretRef:
                name: vmware-exporter

---
kind: Service
apiVersion: v1
metadata:
  name: vmware-exporter
  labels:
    app: vmware-exporter
spec:
  type: ClusterIP
  selector:
    app: vmware-exporter
  ports:
    - protocol: TCP
      name: metrics
      port: 9272
      targetPort: 9272

