apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  labels:
    app.kubernetes.io/instance: argo-cd
    argocd.argoproj.io/instance: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ymmmtym/manifests.git
    targetRevision: HEAD
    path: argo-cd/overlays/dev
    plugin:
      name: kustomize-build-enable-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    # automated:
    #   prune: false
    #   selfHeal: true
    retry:
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 5m0s
      limit: 10
    syncOptions:
    - CreateNamespace=true
  info:
  - name: url
    value: https://argoproj.github.io/
