apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  labels:
    app.kubernetes.io/instance: argo-cd
    argocd.argoproj.io/instance: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: loki-stack
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/ymmmtym/manifests/main/loki-stack/overlays/dev/values.yaml
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.9.9
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 5m0s
      limit: 10
    syncOptions:
    - CreateNamespace=true
