apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  labels:
    app.kubernetes.io/instance: argo-cd
    argocd.argoproj.io/instance: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: longhorn
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/ymmmtym/manifests/main/longhorn/overlays/dev/values.yaml
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.2
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 5m0s
      limit: 10
    syncOptions:
    - CreateNamespace=true
