apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  labels:
    app.kubernetes.io/instance: argo-cd
    argocd.argoproj.io/instance: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vault
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/ymmmtym/manifests/main/vault/overlays/dev/values.yaml
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.26.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 5m0s
      limit: 10
    syncOptions:
    - CreateNamespace=true
