apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  labels:
    app.kubernetes.io/instance: argo-cd
    argocd.argoproj.io/instance: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: velero
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/ymmmtym/manifests/main/velero/overlays/dev/values.yaml
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 2.29.7
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 5m0s
      limit: 10
    syncOptions:
    - CreateNamespace=true
