apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
- name: jaeger-operator
  namespace: monitoring
  includeCRDs: false
  releaseName: jaeger-operator
  version: 2.29.0
  repo: https://jaegertracing.github.io/helm-charts
  valuesFile: values.yaml

