apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-at-home

helmCharts:
- name: whoogle
  namespace: k8s-at-home
  includeCRDs: false
  releaseName: whoogle
  version: 3.3.1
  repo: https://k8s-at-home.com/charts/
  valuesFile: values.yaml

