apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
- name: cilium
  namespace: kube-system
  includeCRDs: true
  releaseName: cilium
  version: 1.14.0
  repo: https://helm.cilium.io/
  valuesFile: values.yaml

