apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argoproj

resources:
- namespace.yaml

helmCharts:
- name: argo-workflows
  namespace: argoproj
  includeCRDs: true
  releaseName: argo-workflows
  # version: latest
  repo: https://argoproj.github.io/argo-helm
  # valuesFile: values.yaml

