apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
- name: vault
  namespace: kube-system
  includeCRDs: false
  releaseName: vault
  # version: latest
  repo: https://helm.releases.hashicorp.com
  # valuesFile: values.yaml

