apiVersion: apps/v1
kind: Deployment
metadata:
  name: inadyn
  labels:
    app: inadyn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inadyn
  template:
    metadata:
      labels:
        app: inadyn
    spec:
      containers:
        - name: inadyn
          image: troglobit/inadyn:latest
          volumeMounts:
            - name: inadyn
              mountPath: /etc/inadyn.conf
              subPath: inadyn.conf
              readOnly: true
      volumes:
      - name: inadyn
        secret:
          secretName: inadyn-secret
          items:
            - key: inadyn.conf
              path: inadyn.conf
