apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chaos-testing

resources:
- namespace.yaml

helmCharts:
- name: chaos-mesh
  namespace: chaos-testing
  includeCRDs: true
  releaseName: chaos-mesh
  # version: latest
  repo: https://charts.chaos-mesh.org
  # valuesFile: values.yaml

