apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
- name: loki
  namespace: monitoring
  includeCRDs: false
  releaseName: loki
  # version: latest
  repo: https://grafana.github.io/helm-charts
  # valuesFile: values.yaml

