apiVersion: v1
kind: Secret
metadata:
  name: client-info-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/local/nas"
type: Opaque
data:
  client-info.yml: Y2xpZW50czoKLSBob3N0OiBuYXMKICBwb3J0OiA1MDAxCiAgaHR0cHM6IHRydWUKICB1c2VybmFtZTogPHVzZXI+CiAgcGFzc3dvcmQ6IDxwYXNzd29yZD4K

---
apiVersion: v1
kind: Secret
metadata:
  name: cifs-csi-credentials
  annotations:
    avp.kubernetes.io/path: "kv/data/local/nas"
type: Opaque
data:
  password: <password | base64encode>
  username: <user | base64encode>

