apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
- namespace.yaml

helmCharts:
- name: ingress-nginx
  namespace: ingress-nginx
  includeCRDs: false
  releaseName: ingress-nginx
  # version: latest
  repo: https://kubernetes.github.io/ingress-nginx
  # valuesFile: values.yaml

