apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
- name: cert-manager
  namespace: kube-system
  includeCRDs: true
  releaseName: cert-manager
  version: latest
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
