apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kubepromsecret
  namespace: prometheus
spec:
  encryptedData:
    password: AgBGfUeQ377Y9b6hv3UJI/GlQLDDTXKSwsbtgI2NWNI6LY49aXmaz25QWv0I/5uaVcKXq81KbwhGnDtGNQkQF/dsoeqjiSwfDOHogHBIGnyKP85n5TdkUUU1uu4dlPUAdlIsuhgRmtFlxwZfG1qjbSdArSVAR1rJmZGuIAude3uohfQ48J5MiLPOGv4DYGY3HHjFgfT4jurbKn7Sot8bFFV2s8RR7W/VjBgm+QUQvwl9TkAQ/UagGPD+6CM9rr2dvffsE8a7dx2O/a2r2VuyM0j/eCZtrOCsxyIcYwhm1Hf5CDkDZj0qVrLw2eG18rCVoIeI1mtl45a7mADG8o6osFtfnPsYOFy+FLPCFSgZhdx30Vh5P1qkz6QgFSNCtIoGHxBfgSh4vxRR9KiTgviAI++ST5vJzymxUOavc5waULQBuLXJboPjgsW2S0GOpNN8rs4DrIRkzeWC8/MFdYSJ2ApIpilOGu1i+HjQFtSlRn9OkGk6lmadcfY87K6ROUtJJIzev8vbsxppRWsOla5fwwPAQIumQ7cgsEuoDqQFnQrTpwyN/GThFaFzSOvphBL3Mz0VNui2xK1OulEUzknhvsdR3YAFIemVKAx3JbjFJsNKIcd4Ot/awaMFvPmtG/WTvNB02ybthlQiN9enn+cliLgd0Nr7J3+hVRjukcAS7UIz+I7Q1pBGEhH0LH/wFHRtTwZL1/o8YSucvla5BD4Banpbn7R2Ox5YcUbG5MTJIWThFMtba979mkoDJdW9+A+NFLEqcd0hjq2ohc2UsYxpgWty/bE11PeuX2DQd7bXKRhhjJNrt+nAB7ADAvWK8d8ch/4=
    username: AgCaiht0k96HH9fgJjtgu8Nm8qW2FiI3xsWIRAFZ8fyi1x4TJsy64ZyRx3j2ULCLrVMQtfY8mXAaIWZdrw/6HGnyKKLTjErbsax8ScG8K2/9UWfa2Gyp+wfseBAMPpEGakqRiPTj1wDVkNlf8a+qm/0tbmfzA3enYAPspj2p0eVO+WBPVxrQ5Jr3AJOnwuKsupgOeQqnghZhXxbH3pT5deatE/2skzhwtICttUaeXaAbYclYUdT9/4qhINUtJ1iPx4l0DISo70yjkXGVlfPam6rhr/DLb2Yol8CEj9ZAyzVG1kaxp2t4YmlnpejnM7Iq8L1eQp8aiHxRc6kGQ4UYKZ4GxNjG/r1KcsO2FAZ6H9CwakQtZsaUpRCmLhy6LkVOp4LbWGI+ntEtA7fgXtBvl8gvzCcxq9J3YOfTT457BjxYfahe6btDuZwX3me8ud8I2dVfcHINzjFLhDgc8w4RGUZDR4lTBZD+1UV+s2pLgSYKutrV8N901HNiIQQu9i4487Xd2Z1OQUl2TAZat/O1fOziGG5fun2kJZsKIKasDoRRoZv9likW23ug9VjWeziADExsaJ/Zfa9dOx77HRTH/8ump4JoSYoXKP1DMXiCRufSEk86/VkmEdvEMp1MS8XgdwEVcYn26ZlcaWxflKsTjNu/A2CQ0z3QhuRUbuiOAAtxZusurIm65nMiQ6Wu3hYKrGS5uVyiUyw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: kubepromsecret
      namespace: prometheus
    type: Opaque

