apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kubepromsecret
  namespace: prometheus
spec:
  encryptedData:
    password: AgA3Ch8rUdnLmZX5mih8o3yiJdaOZKNB7ejOYVTZrlH6QHpvnLoykKKxcfstZd9R12IWjKzPx6Lr6XymgIraEs1qYYKzRqLanBqfDJVCscX2aPgpmp21WJvX8wQUWEO7Y5+nXH29lel2xmUuRpA9eoGGx1Sxsd3Aw3Qhe7yBjELgCSa8fvNKrosXN5JcixkVJ9EYxjr0pQH3aqJppHMWxkfpOi9eHThO0nHUszjiC5xbaoPXSeJeVjULZVC9ENNErEHs33hxUpJvltAr0PfcHLR0zBgnG0g0JpfITmyxXQ71Uw8FuMXPSLt3yYjDrF+DoJXp3aPfkdwUEfzPyFiPtUkFA1XkZUeosXLz0sppo4ADRm2r/TcYBG+Gzx1CLdyF73Y/xaGVMRS/DDmYAEtcZBXV9jPEcwR5uPSUJr780sHaps+IJmo2H4BOq2GGwZHdYGyADYNGB9nSDjTdZ6UEGRJdwWYV0vwPrthLTyJuFgOl0zPbb8ujxH5a3XVWT27E9LK2GK/yLAHXSH8VEWbGy5+qPDQpc9IDu/EaWJI+wb8yc+ILZ8D9Lp/44yyhc85ki3i6MLHswQB59S/Yodw6Jhi4rs5L+Mu3TqCFFyEF4Lt7bpIOO5XRpvs16/Ews8YAn+PqIwrWk9Vag/syU87xNWcsaogTg/74Qlwkv7yjpBKJ988fgWclKRFmA8vQQWu9QeHwr1fyXy+rGr35LRTPd2W2m0PgL0HTgU9Kne2RZLLjw3OuDPkSSJ/7sZ3izC6KkCJRWb+1taj7rdoLZEsu5JP5uNo3HX9fUNwAWdXRJR7PSO1C3pIQj47V10YIE59Al+E=
    username: AgBYDixBLbMbSpBrNikxTuKaBh+vYP5rp0oRVC7QYfRMYLZF0iu6vYr08/Rp25WgNpi84QwQO5tC9y/3dpWMHlXKhpS8L+K2HnU0eG46QK4vCrxKvpAaifuXOWAyTHxyMGLy0szVlsz/liV2xqEWoI6lqqy1MGVpfBv02rb/6xLqIBofCI81kk43E3Oa6qK/q6qZoX+nUQz41yTBdA27OiNumS3IXtFe+aiT1RNqz+ncbn+H403oaG7xJKPsmf9kpuPUb2icUgcATq8HGl6mMCbqPR6/WlzzKwGHchwgUT4q/OW7pYsaGIQSKlrrWOtiOWp2QcX9XifNoqYhrdeL0PFG6y3vzEF6e3zSAjorKKFztKokDdQoD7WLBoQLD1oqdJaONhIUdVvgP7ST+amQiOZqX71BTSXi/IJFVPAN+9hWvUYGMDI6ZK7srAmLgxxUYz9V/bfI4A7WSN8F4AlmGZGnvfGbh7mb2mOOW7rRxGiQLqVJGnE5WRPEYd51v6xvK7PGvE4UDfv8OyFBGZ8RM74JBED3JajJGXMg6Mh8CkYGnWZBD+nkvQRwivQo2XAIbhC2K20GNcsgKFFUHqxtZdUH+a5djnLsN4PEwc0J2x+fSbjHpylHj0Gc1WRWpgyD5mbCWJQ2dieo4SYLI3aXqfrRbjHgF83rciadHBkKOmHhh0BQgb17IhIlCkm9xWaHb/rMQQuoURE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: kubepromsecret
      namespace: prometheus
    type: Opaque

