apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-at-home

helmCharts:
- name: speedtest-exporter
  namespace: k8s-at-home
  includeCRDs: false
  releaseName: speedtest-exporter
  version: 5.2.0
  repo: https://k8s-at-home.com/charts/
  valuesFile: values.yaml

