apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
- name: speedtest-exporter
  namespace: monitoring
  includeCRDs: false
  releaseName: speedtest-exporter
  # version: latest
  repo: https://k8s-at-home.com/charts/
  # valuesFile: values.yaml

