injector:
  enabled: false

server:
  image:
    pullPolicy: Always

  updateStrategyType: "RollingUpdate"

  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - host: cluster.yumenomatayume.home
        paths:
          - /

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: longhorn

  ha:
    enabled: true
    raft:
      enabled: true

ui:
  enabled: true
