apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml

helmCharts:
- name: argo-cd
  namespace: argocd
  includeCRDs: true
  releaseName: argo-cd
  # version: latest
  repo: https://argoproj.github.io/argo-helm
  # valuesFile: values.yaml

