apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-notebook
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: jupyter-notebook
    repoURL: 'https://github.com/ymmmtym/manifests'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
