apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
spec:
  destination:
    name: ''
    namespace: rook-ceph
    server: 'https://kubernetes.default.svc'
  source:
    path: rook-ceph
    repoURL: 'https://github.com/ymmmtym/manifests'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
