apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- namespace.yaml

helmCharts:
- name: jaeger
  namespace: monitoring
  includeCRDs: false
  releaseName: jaeger
  # version: latest
  repo: https://jaegertracing.github.io/helm-charts
  # valuesFile: values.yaml

