defaultSettings:
  defaultDataPath: /mnt/disk01

ingress:
  enabled: true
  ingressClassName: nginx
  host: cluster.yumenomatayume.home
  path: /longhorn(/|$)(.*)
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
