repositories:
  - name: metallb
    url: https://metallb.github.io/metallb

templates:
  default: &default
    chart: metallb/{{`{{ .Release.Name }}`}}
    namespace: metallb
    values:
      - "./environments/{{ .Environment.Name }}/values*.yaml"

releases:
  - name: metallb
    <<: *default
