apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- ../../base
- secret.yaml
- service-monitor.yaml

images:
- name: pryorda/vmware_exporter
  newTag: v0.18.3

