apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vmware-exporter
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
    interval: 30s
    scrapeTimeout: 10s
  selector:
    matchLabels:
      app: vmware-exporter
  namespaceSelector:
    any: false
    matchNames:
    - monitoring

