loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 10Gi

promtail:
  enabled: true
  config:
    lokiAddress: http://{{ .Release.Name }}:3100/loki/api/v1/push

