apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

helmCharts:
- name: sealed-secrets
  namespace: sealed-secrets
  includeCRDs: true
  releaseName: sealed-secrets
  # version: latest
  repo: https://bitnami-labs.github.io/sealed-secrets
  # valuesFile: values.yaml

