apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-cd
  namespace: argo-cd
  includeCRDs: true
  releaseName: argo-cd
  version: 4.5.7
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml

labels:
- pairs:
    app.kubernetes.io/instance: argo-cd

