apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-at-home

helmCharts:
- name: minecraft
  namespace: k8s-at-home
  includeCRDs: false
  releaseName: minecraft
  # version: latest
  repo: https://itzg.github.io/minecraft-server-charts/
  # valuesFile: values.yaml

