apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: purelb

resources:
- namespace.yaml

helmCharts:
- name: purelb
  namespace: purelb
  includeCRDs: true
  releaseName: purelb
  # version: latest
  repo: https://gitlab.com/api/v4/projects/20400619/packages/helm/stable
  # valuesFile: values.yaml

