apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    subnet: '192.168.100.128/25'
    pool: '192.168.100.128-192.168.100.254'
    aggregation: default
