---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stg
spec:
  acme:
    email: yumenomatayume@yumenomatayume.net
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-stg-account-key
    solvers:
    - http01:
        ingress:
          class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-stg
  namespace: kube-system
spec:
  secretName: letsencrypt-stg
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - yumenomatayume
  commonName: home.yumenomatayume.net
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  usages:
    - server auth
    - client auth
  dnsNames:
    - home.yumenomatayume.net
  issuerRef:
    name: letsencrypt-stg
    kind: ClusterIssuer
    group: cert-manager.io

