---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned
  namespace: kube-system
spec:
  isCA: true
  commonName: yumenomatayume.home
  secretName: selfsigned
  privateKey:
    algorithm: RSA
    size: 4096
  dnsNames:
    - "*.yumenomatayume.home"
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: kube-system
spec:
  ca:
    secretName: cert-manager-selfsigned

