repositories:
  - name: jetstack
    url: https://charts.jetstack.io

templates:
  default: &default
    chart: jetstack/{{`{{ .Release.Name }}`}}
    namespace: cert-manager
    values:
      - "./environments/{{ .Environment.Name }}/values*.yaml"

releases:
  - name: cert-manager
    <<: *default
  - name: kustomize
    namespace: prometheus
    chart: ./base
    disableValidation: true
