apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-at-home

helmCharts:
- name: calibre-web
  namespace: k8s-at-home
  includeCRDs: false
  releaseName: calibre-web
  # version: latest
  repo: https://k8s-at-home.com/charts/
  # valuesFile: values.yaml

